ТЗ первой недели
Link789/loft-taxi pull request #2
Opened 2022-08-19 17:00 UTC by Link789

1. Созданы страницы: Логин, Регистрация, Карта, Профиль
2. Настроено последовательное логическое отображение компонентов без роутинга
3. Добавлены логотипы и стили

![image](https://user-images.githubusercontent.com/33423673/185669853-49a8cbe2-6b46-42e7-813b-f03c3bb83a04.png)

![image](https://user-images.githubusercontent.com/33423673/185669981-11b214d9-6c96-4f1c-990c-911dc67e6913.png)

![image](https://user-images.githubusercontent.com/33423673/185670078-493c3c4d-d10c-4e2a-bb3c-c35e7d4e87db.png)

2022-08-22 07:27 UTC, nlold requested changes
Очень хороший PR. Композиция компонентов, соответствие макетов и правильный роутинг — однозначно лайк!

На будущее — не забывай просматривать PR непостредственно перед его созданием, на предмет банальных штук (консольл логи, неиспользуемые переменные и тому подобное) — это сократит время на ревью и уменьшит кол-во банальныз правок.

И еще. Директорию .idea лучше сразу закидывать в .gitignore и файлы внутри папки создавать для себя. Так как в реальной работе разные разработчики пользуются разными инструментами и тянуть в проект специфические штуки для конкретной IDE не очень хорошая практика. Но в рамках этого проекта, если хочешь, можешь оставить.

2022-08-22 07:27 UTC, nlold commented on src/App.css
> +#loginForm button#login:hover {
На будущее — лучше уже сейчас начинать создавать отдельные css файлы для каждой страницы, чтобы не хратить все стили в одном файле и не терять в читаемости кода в будущем.

2022-08-22 07:27 UTC, nlold commented on src/components/Header.jsx
> +        //console.log(event.target.attributes[1].value);
Не забывай подчищать такие штуки =)

2022-08-22 07:27 UTC, nlold commented on src/components/Header.jsx
> +                <div style={{
Стили лучше сразу выносить в css классы, а не писать внутри компонента. Иначе потом можно будет потерять контроль и запутатся в коде.

2022-08-22 07:27 UTC, nlold commented on src/components/Header.jsx
> +        switch (this.state.page) {
Очень хороший подход к роутингу — однозначно лайк!

2022-08-22 07:27 UTC, nlold commented on src/components/Header.jsx
> +                return <LoginPage/>
Лучше такой кейс обработать внутри функции getPage, чтобы в switch все было единообразно.

2022-08-22 07:27 UTC, nlold commented on src/components/pages/Registration.jsx
> +        console.log(this.state.lastName, this.state.password, this.state.isRegistration);
И такое штуки не забывай удалять в PR =)

2022-08-22 07:27 UTC, nlold commented on src/components/pages/Registration.jsx
> +    handleClick(event) {
Не используемые аргументы лучше вовсе не писать.

2022-08-22 07:27 UTC, nlold commented on src/components/pages/Registration.jsx
> +                        backgroundImage: `url(${MapImg})`
Тут тоже стили лучше вынести в css.

2022-08-22 07:27 UTC, nlold commented on src/components/pages/Login.jsx
> +        console.log(this.state.userName, this.state.password, this.state.isLogin);
Аналогично

2022-08-22 07:27 UTC, nlold commented on src/components/pages/Login.jsx
> +    handleClick(event) {
Аналогично

2022-08-22 07:27 UTC, nlold commented on src/components/pages/Login.jsx
> +                        backgroundImage: `url(${MapImg})`
Аналогично

2022-08-31 16:07 UTC, closed without merging

2022-08-31 16:08 UTC, Link789 commented
До устранения замечаний